Fixed some typos
elisaado/somtoday.js pull request #18
Opened 2024-07-28 19:37 UTC by 7ijme

I fixed some minor typos.

2024-07-28 19:40 UTC, 112batman requested changes
verder goed

2024-07-28 19:40 UTC, 112batman commented on src/managers/AppointmentManager.ts
> +   * @param {number|AppointmentQueryOptions} [appointment] The id of the appointment to fetch, or query parameter.
Moet wel meervoud zijn

2024-07-28 19:48 UTC, 7ijme commented
gefixt !!

2024-07-28 19:48 UTC, 112batman approved these changes
lgtm

2024-07-28 19:49 UTC, 7ijme commented
lgtm

2024-08-16 11:38 UTC, JxxIT commented
lgtm

2024-08-16 11:42 UTC, elisaado commented
lgtm

2025-02-03 20:41 UTC, merged